#!/usr/bin/env bash
# Cursor cloud agent start script for HogHunter.
#
# Runs every time a Cursor cloud agent boots.  Installed disk state persists,
# but exported shell variables do NOT, so secrets fetched from Infisical are
# written to disk here and re-exported by a tiny .source.sh helper.
#
# Required Cursor dashboard secrets (org-wide):
#   - INFISICAL_CLIENT_ID
#   - INFISICAL_CLIENT_SECRET
#
# Output:
#   - $HOME/.cursor-cloud-env/HogHunter.env        (mode 0600, KEY=VALUE lines)
#   - $HOME/.cursor-cloud-env/HogHunter.source.sh  (sourced to export the env)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_BASENAME="$(basename "$REPO_ROOT")"
ENV_DIR="$HOME/.cursor-cloud-env"
ENV_FILE="$ENV_DIR/${REPO_BASENAME}.env"
SOURCE_FILE="$ENV_DIR/${REPO_BASENAME}.source.sh"
INFISICAL_ENV_FILE="$REPO_ROOT/.cursor/infisical.env"

mkdir -p "$ENV_DIR"
chmod 0700 "$ENV_DIR"

# ── Load non-secret Infisical project metadata from the repo ──
if [ -f "$INFISICAL_ENV_FILE" ]; then
  # shellcheck disable=SC1090
  set -a; . "$INFISICAL_ENV_FILE"; set +a
fi

PROJECT_ID="${INFISICAL_PROJECT_ID:-}"
INFISICAL_ENV_VALUE="${INFISICAL_ENV:-prod}"
INFISICAL_DOMAIN_VALUE="${INFISICAL_DOMAIN:-https://app.infisical.com}"

# ── Guard: prod only (owner, 2026-10-10) ──
# The dev and staging Infisical environments are retired.  Refuse to export
# anything from another environment, whether the value came from
# .cursor/infisical.env or from the session environment.
if [ "$INFISICAL_ENV_VALUE" != "prod" ]; then
  echo "==> ERROR: INFISICAL_ENV is '$INFISICAL_ENV_VALUE'; only 'prod' is allowed (dev and staging are retired)." >&2
  exit 1
fi

# ── Guard: dashboard secrets must be present ──
if [ -z "${INFISICAL_CLIENT_ID:-}" ] || [ -z "${INFISICAL_CLIENT_SECRET:-}" ]; then
  echo "==> INFISICAL_CLIENT_ID and INFISICAL_CLIENT_SECRET are not set in this Cursor cloud session." >&2
  echo "==> Add them as org-wide / team secrets in the Cursor dashboard to load HogHunter app secrets." >&2
  echo "==> Continuing with no secret export (agent boot will not fail)."
  exit 0
fi

if [ -z "$PROJECT_ID" ]; then
  echo "==> ERROR: INFISICAL_PROJECT_ID is empty; check .cursor/infisical.env." >&2
  exit 1
fi

# ── Fetch secrets ──
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

fetch_with_cli() {
  infisical export \
      --projectId "$PROJECT_ID" \
      --env "$INFISICAL_ENV_VALUE" \
      --domain "$INFISICAL_DOMAIN_VALUE" \
      --plain \
      >"$TMP" 2>/dev/null
}

fetch_with_api() {
  # Authenticate via universal-auth, fetch all keys per env, never echo them.
  local token
  token="$(curl -fsS -X POST \
      "$INFISICAL_DOMAIN_VALUE/api/v1/auth/universal-auth/login" \
      -H 'Content-Type: application/json' \
      -d "{\"clientId\":\"$INFISICAL_CLIENT_ID\",\"clientSecret\":\"$INFISICAL_CLIENT_SECRET\"}" \
      | python3 -c 'import json,sys; print(json.load(sys.stdin)["accessToken"], end="")')"
  curl -fsS \
      "$INFISICAL_DOMAIN_VALUE/api/v3/secrets/raw?workspaceId=$PROJECT_ID&environment=$INFISICAL_ENV_VALUE&secretPath=/" \
      -H "Authorization: Bearer $token" \
      | python3 -c '
import json, sys, urllib.parse
data = json.load(sys.stdin)
for item in data.get("secrets", []):
    key = item["secretKey"]
    val = item["secretValue"]
    print(f"{key}={val}")
' >"$TMP"
}

if command -v infisical >/dev/null 2>&1; then
  if ! fetch_with_cli; then
    echo "==> WARN: infisical CLI export failed; falling back to API fetch." >&2
    fetch_with_api
  fi
else
  fetch_with_api
fi

if [ ! -s "$TMP" ]; then
  echo "==> ERROR: no secrets fetched from Infisical for project $PROJECT_ID env=$INFISICAL_ENV_VALUE." >&2
  exit 1
fi

# ── Persist env file (0600) and source helper ──
umask 077
mv "$TMP" "$ENV_FILE"
chmod 0600 "$ENV_FILE"
trap - EXIT

cat >"$SOURCE_FILE" <<'SH'
#!/usr/bin/env bash
# Auto-generated by scripts/cursor-cloud-start.sh.  Source this file to
# export the HogHunter Infisical secrets for the current shell session.
set -a
. "$HOME/.cursor-cloud-env/HogHunter.env"
set +a
SH
chmod 0600 "$SOURCE_FILE"

echo "==> Loaded $(grep -c '=' "$ENV_FILE" 2>/dev/null || echo 0) secrets into $ENV_FILE (mode 0600)."
echo "==> Source with: . $SOURCE_FILE"
